package com.example.androidapp.domain.repository

import com.example.androidapp.domain.util.ShareCodeUtil

/**
 * Repository interface for managing quiz share codes.
 *
 * Share codes are 6-character uppercase alphanumeric strings generated by [ShareCodeUtil]
 * that allow users to share quizzes without exposing internal quiz IDs.
 * Share codes are stored remotely only (no local Room caching).
 */
interface ShareCodeRepository {

    /**
     * Looks up the quiz ID associated with a share code.
     *
     * @param shareCode The 6-character share code to look up.
     * @return [Result] containing the quiz ID, or null if the code does not exist.
     */
    suspend fun lookupQuizId(shareCode: String): Result<String?>

    /**
     * Generates a unique 6-character alphanumeric share code for a quiz.
     *
     * Retries up to 10 times to ensure uniqueness. Fails if a unique code
     * cannot be generated within the retry limit.
     *
     * @param quizId The ID of the quiz to generate a share code for.
     * @return [Result] containing the generated share code string on success.
     */
    suspend fun generateShareCode(quizId: String): Result<String>

    /**
     * Deletes a share code mapping, typically called on permanent quiz deletion.
     *
     * @param shareCode The share code to remove.
     * @return [Result] indicating success or failure.
     */
    suspend fun deleteShareCode(shareCode: String): Result<Unit>

    /**
     * Creates a new share code for a quiz and deletes the old one.
     *
     * The new code is persisted first to avoid a window where no code exists.
     *
     * @param quizId The ID of the quiz to regenerate the code for.
     * @param oldShareCode The existing share code to replace.
     * @return [Result] containing the new share code string on success.
     */
    suspend fun regenerateShareCode(quizId: String, oldShareCode: String): Result<String>

    /**
     * Validates whether a share code exists and is associated with an accessible quiz.
     *
     * @param shareCode The 6-character share code to validate.
     * @return [Result] containing the associated quiz ID if the code is valid,
     *         or a failure if the code does not exist or is invalid.
     */
    suspend fun validateShareCode(shareCode: String): Result<String>
}
